package com.ruptura.app.domain.model

data class FocusSession(
    val id: Long = 0,                   // Auto-generated by Room
    val config: SessionConfig,
    val state: SessionState,
    val currentCycle: Int,              // Current cycle number (1-based)
    val currentPhase: SessionPhase,
    val phaseStartTime: Long,           // Timestamp when current phase started
    val phaseEndTime: Long,             // Timestamp when current phase should end
    val totalFocusTimeMillis: Long = 0, // Accumulated actual focus time
    val breakCount: Int = 0,            // Number of times user broke focus
    val createdAt: Long = System.currentTimeMillis(),
    val spiritualActivityId: String? = null  // Links to spiritual activity if session started from one
)

enum class SessionState {
    SETUP,          // User configuring
    FOCUS_ACTIVE,   // Focus time, screen locked
    BREAK_ACTIVE,   // Break time, screen unlocked
    PAUSED,         // Between cycles, showing countdown
    COMPLETED,      // All cycles finished
    CANCELLED       // User ended early
}

enum class SessionPhase {
    FOCUS,
    BREAK,
    INTER_CYCLE_PAUSE  // The "Next focus starts in 10...9..." phase
}
